import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Aria Portable Bluetooth Speaker",
    sku: "ARI-BS-016",
    category: "Electronics",
    warehouse: "Dhaka Main DC",
    onHand: 0,
    reserved: 0,
    incoming: 60,
    alertAt: 20,
    capacity: 60,
    velocity: 6,
    unitCost: 72,
    restockedAt: "2026-08-22",
    coverDays: null,
    suggested: 0,
  },
  {
    id: "p2",
    name: "Halo Smart Bulb Starter Pack",
    sku: "HAL-SB-023",
    category: "Electronics",
    warehouse: "Dhaka Main DC",
    onHand: 0,
    reserved: 0,
    incoming: 0,
    alertAt: 25,
    capacity: 80,
    velocity: 18,
    unitCost: 14,
    restockedAt: "2026-08-18",
    coverDays: null,
    suggested: 50,
  },
  {
    id: "p3",
    name: "Aurora Wireless Charging Pad",
    sku: "AUR-WC-008",
    category: "Electronics",
    warehouse: "Dhaka Main DC",
    onHand: 4,
    reserved: 1,
    incoming: 0,
    alertAt: 18,
    capacity: 40,
    velocity: 14,
    unitCost: 21,
    restockedAt: "2026-08-28",
    coverDays: 0.2,
    suggested: 35,
  },
  {
    id: "p4",
    name: "Lumen Minimal Desk Lamp",
    sku: "LUM-DL-021",
    category: "Home & Living",
    warehouse: "Chattogram Hub",
    onHand: 6,
    reserved: 2,
    incoming: 24,
    alertAt: 15,
    capacity: 40,
    velocity: 17,
    unitCost: 55,
    restockedAt: "2026-09-08",
    coverDays: 0.2,
    suggested: 0,
  },
  {
    id: "p5",
    name: "Vega Insulated Sport Bottle",
    sku: "VEG-BT-031",
    category: "Sports",
    warehouse: "Khulna Depot",
    onHand: 9,
    reserved: 1,
    incoming: 30,
    alertAt: 20,
    capacity: 60,
    velocity: 16,
    unitCost: 8,
    restockedAt: "2026-09-06",
    coverDays: 0.5,
    suggested: 5,
  },
  {
    id: "p6",
    name: "Drift Ergonomic Office Chair",
    sku: "DRF-OC-004",
    category: "Home & Living",
    warehouse: "Sylhet Fulfilment",
    onHand: 12,
    reserved: 3,
    incoming: 0,
    alertAt: 6,
    capacity: 30,
    velocity: 4,
    unitCost: 250,
    restockedAt: "2026-09-05",
    coverDays: 21,
    suggested: 0,
  },
  {
    id: "p7",
    name: "Nomad Leather Weekender Bag",
    sku: "NOM-BG-007",
    category: "Fashion",
    warehouse: "Chattogram Hub",
    onHand: 18,
    reserved: 3,
    incoming: 0,
    alertAt: 20,
    capacity: 40,
    velocity: 15,
    unitCost: 140,
    restockedAt: "2026-09-09",
    coverDays: 1,
    suggested: 25,
  },
  {
    id: "p8",
    name: "Cirrus Alpaca Throw Blanket",
    sku: "CIR-TB-005",
    category: "Home & Living",
    warehouse: "Sylhet Fulfilment",
    onHand: 24,
    reserved: 2,
    incoming: 0,
    alertAt: 10,
    capacity: 50,
    velocity: 8,
    unitCost: 62,
    restockedAt: "2026-09-07",
    coverDays: 21,
    suggested: 0,
  },
  {
    id: "p9",
    name: "Vega Smart Fitness Watch",
    sku: "VEG-SW-014",
    category: "Electronics",
    warehouse: "Dhaka Main DC",
    onHand: 32,
    reserved: 4,
    incoming: 40,
    alertAt: 40,
    capacity: 60,
    velocity: 22,
    unitCost: 120,
    restockedAt: "2026-09-11",
    coverDays: 1.2,
    suggested: 10,
  },
  {
    id: "p10",
    name: "Terra Ceramic Mug Set",
    sku: "TER-MG-012",
    category: "Home & Living",
    warehouse: "Sylhet Fulfilment",
    onHand: 46,
    reserved: 5,
    incoming: 0,
    alertAt: 18,
    capacity: 80,
    velocity: 11,
    unitCost: 20,
    restockedAt: "2026-09-12",
    coverDays: 28,
    suggested: 0,
  },
  {
    id: "p11",
    name: "Orbit Noise-Cancel Headphones",
    sku: "ORB-HP-002",
    category: "Electronics",
    warehouse: "Dhaka Main DC",
    onHand: 58,
    reserved: 6,
    incoming: 0,
    alertAt: 20,
    capacity: 90,
    velocity: 13,
    unitCost: 145,
    restockedAt: "2026-09-14",
    coverDays: 30,
    suggested: 0,
  },
  {
    id: "p12",
    name: "Pace Lightweight Running Shorts",
    sku: "PAC-RS-019",
    category: "Sports",
    warehouse: "Khulna Depot",
    onHand: 64,
    reserved: 4,
    incoming: 0,
    alertAt: 24,
    capacity: 100,
    velocity: 19,
    unitCost: 16,
    restockedAt: "2026-09-10",
    coverDays: 23,
    suggested: 0,
  },
  {
    id: "p13",
    name: "Linen Weave Bath Towel",
    sku: "LIN-BT-027",
    category: "Home & Living",
    warehouse: "Chattogram Hub",
    onHand: 75,
    reserved: 8,
    incoming: 0,
    alertAt: 30,
    capacity: 120,
    velocity: 21,
    unitCost: 22,
    restockedAt: "2026-09-13",
    coverDays: 24,
    suggested: 0,
  },
  {
    id: "p14",
    name: "Solace Scented Candle",
    sku: "SOL-SC-033",
    category: "Home & Living",
    warehouse: "Sylhet Fulfilment",
    onHand: 88,
    reserved: 6,
    incoming: 0,
    alertAt: 35,
    capacity: 140,
    velocity: 26,
    unitCost: 12,
    restockedAt: "2026-09-15",
    coverDays: 22,
    suggested: 0,
  },
  {
    id: "p15",
    name: "Crest Organic Cotton Tee",
    sku: "CRE-CT-009",
    category: "Fashion",
    warehouse: "Chattogram Hub",
    onHand: 96,
    reserved: 9,
    incoming: 0,
    alertAt: 40,
    capacity: 160,
    velocity: 31,
    unitCost: 9,
    restockedAt: "2026-09-16",
    coverDays: 20,
    suggested: 0,
  },
  {
    id: "p16",
    name: "Nimbus Packable Rain Jacket",
    sku: "NIM-RJ-021",
    category: "Fashion",
    warehouse: "Khulna Depot",
    onHand: 230,
    reserved: 7,
    incoming: 0,
    alertAt: 30,
    capacity: 200,
    velocity: 5,
    unitCost: 86,
    restockedAt: "2026-09-02",
    coverDays: 60,
    suggested: 0,
  },
];