// app/(dashboard)/supplierdashboard/orders/shipped/shippedData.ts

import { ShippedOrder } from "./types";

// Replace with data fetched from your API layer / database
export const SHIPPED_ORDERS: ShippedOrder[] = [
  {
    id: "so1",
    orderNumber: "ORD-10245",
    customerName: "Farhana Akter",
    customerPhone: "01712-345678",
    deliveryAddress: "House 12, Road 5, Dhanmondi",
    city: "Dhaka",
    productName: "Wireless ANC Headphones",
    quantity: 1,
    courier: "Pathao Courier",
    trackingId: "PC-88213456",
    shippedDate: "2026-09-19",
    expectedDelivery: "2026-09-22",
    orderValue: 3200,
    paymentMethod: "Prepaid",
    status: "in_transit",
  },
  {
    id: "so2",
    orderNumber: "ORD-10238",
    customerName: "Tanvir Hasan",
    customerPhone: "01898-221144",
    deliveryAddress: "Sector 7, Uttara",
    city: "Dhaka",
    productName: "Smart Fitness Band",
    quantity: 2,
    courier: "Steadfast",
    trackingId: "SF-77102938",
    shippedDate: "2026-09-18",
    expectedDelivery: "2026-09-21",
    orderValue: 4500,
    paymentMethod: "COD",
    status: "out_for_delivery",
  },
  {
    id: "so3",
    orderNumber: "ORD-10221",
    customerName: "Mst. Sultana Razia",
    customerPhone: "01611-778899",
    deliveryAddress: "GEC Circle",
    city: "Chattogram",
    productName: "Portable Blender",
    quantity: 1,
    courier: "RedX",
    trackingId: "RX-56231190",
    shippedDate: "2026-09-16",
    expectedDelivery: "2026-09-20",
    orderValue: 1850,
    paymentMethod: "COD",
    status: "delayed",
  },
  {
    id: "so4",
    orderNumber: "ORD-10255",
    customerName: "Rakibul Islam",
    customerPhone: "01911-556677",
    deliveryAddress: "Shaheb Bazar",
    city: "Rajshahi",
    productName: "Wireless ANC Headphones",
    quantity: 1,
    courier: "Sundarban Courier",
    trackingId: "SB-33421678",
    shippedDate: "2026-09-20",
    expectedDelivery: "2026-09-23",
    orderValue: 3200,
    paymentMethod: "Prepaid",
    status: "shipped",
  },
  {
    id: "so5",
    orderNumber: "ORD-10202",
    customerName: "Nusrat Jahan",
    customerPhone: "01755-990011",
    deliveryAddress: "Zindabazar",
    city: "Sylhet",
    productName: "Smart Fitness Band",
    quantity: 1,
    courier: "Pathao Courier",
    trackingId: "PC-88209981",
    shippedDate: "2026-09-14",
    expectedDelivery: "2026-09-17",
    orderValue: 2250,
    paymentMethod: "COD",
    status: "delayed",
  },
  {
    id: "so6",
    orderNumber: "ORD-10260",
    customerName: "Imran Kabir",
    customerPhone: "01633-112233",
    deliveryAddress: "Khulshi",
    city: "Chattogram",
    productName: "Portable Blender",
    quantity: 1,
    courier: "RedX",
    trackingId: "RX-56239012",
    shippedDate: "2026-09-21",
    expectedDelivery: "2026-09-24",
    orderValue: 1850,
    paymentMethod: "Prepaid",
    status: "shipped",
  },
  {
    id: "so7",
    orderNumber: "ORD-10247",
    customerName: "Sadia Islam",
    customerPhone: "01844-667788",
    deliveryAddress: "Boyra",
    city: "Khulna",
    productName: "Smart Fitness Band",
    quantity: 3,
    courier: "Steadfast",
    trackingId: "SF-77108845",
    shippedDate: "2026-09-19",
    expectedDelivery: "2026-09-22",
    orderValue: 6750,
    paymentMethod: "COD",
    status: "in_transit",
  },
];